//
// AcquisitionAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AcquisitionAPI {

    /**
     Record an app download / first open
     
     - parameter xGtmGrowthKey: (header) SDK write key issued from the GTM Easy dashboard for this app. 
     - parameter downloadRequest: (body)  
     - returns: DownloadResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func downloadsPost(xGtmGrowthKey: String, downloadRequest: DownloadRequest) async throws -> DownloadResponse {
        return try await downloadsPostWithRequestBuilder(xGtmGrowthKey: xGtmGrowthKey, downloadRequest: downloadRequest).execute().body
    }

    /**
     Record an app download / first open
     - POST /downloads
     - Records an `acquisition.app_download` event and fires the configured Discord notification (unless the IP is Apple/Google review infrastructure).
     - parameter xGtmGrowthKey: (header) SDK write key issued from the GTM Easy dashboard for this app. 
     - parameter downloadRequest: (body)  
     - returns: RequestBuilder<DownloadResponse> 
     */
    open class func downloadsPostWithRequestBuilder(xGtmGrowthKey: String, downloadRequest: DownloadRequest) -> RequestBuilder<DownloadResponse> {
        let localVariablePath = "/downloads"
        let localVariableURLString = GTMEasyGrowthAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: downloadRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "x-gtm-growth-key": xGtmGrowthKey.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DownloadResponse>.Type = GTMEasyGrowthAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Record a new app user registration
     
     - parameter xGtmGrowthKey: (header) SDK write key issued from the GTM Easy dashboard for this app. 
     - parameter registrationRequest: (body)  
     - returns: RegistrationResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func registrationsPost(xGtmGrowthKey: String, registrationRequest: RegistrationRequest) async throws -> RegistrationResponse {
        return try await registrationsPostWithRequestBuilder(xGtmGrowthKey: xGtmGrowthKey, registrationRequest: registrationRequest).execute().body
    }

    /**
     Record a new app user registration
     - POST /registrations
     - Identifies the user (upserts traits + People geo from Cloudflare) AND records an `acquisition.user_registered` event, then fires the configured Discord notification (unless the IP is Apple/Google review infrastructure).
     - parameter xGtmGrowthKey: (header) SDK write key issued from the GTM Easy dashboard for this app. 
     - parameter registrationRequest: (body)  
     - returns: RequestBuilder<RegistrationResponse> 
     */
    open class func registrationsPostWithRequestBuilder(xGtmGrowthKey: String, registrationRequest: RegistrationRequest) -> RequestBuilder<RegistrationResponse> {
        let localVariablePath = "/registrations"
        let localVariableURLString = GTMEasyGrowthAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: registrationRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "x-gtm-growth-key": xGtmGrowthKey.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RegistrationResponse>.Type = GTMEasyGrowthAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
