//
// AttributionAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AttributionAPI {

    /**
     Submit an Apple Search Ads attribution token
     
     - parameter xGtmGrowthKey: (header) SDK write key issued from the GTM Easy dashboard for this app. 
     - parameter appleAttributionRequest: (body)  
     - returns: IngestEventResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func attributionAppleSearchAdsPost(xGtmGrowthKey: String, appleAttributionRequest: AppleAttributionRequest) async throws -> IngestEventResponse {
        return try await attributionAppleSearchAdsPostWithRequestBuilder(xGtmGrowthKey: xGtmGrowthKey, appleAttributionRequest: appleAttributionRequest).execute().body
    }

    /**
     Submit an Apple Search Ads attribution token
     - POST /attribution/apple-search-ads
     - parameter xGtmGrowthKey: (header) SDK write key issued from the GTM Easy dashboard for this app. 
     - parameter appleAttributionRequest: (body)  
     - returns: RequestBuilder<IngestEventResponse> 
     */
    open class func attributionAppleSearchAdsPostWithRequestBuilder(xGtmGrowthKey: String, appleAttributionRequest: AppleAttributionRequest) -> RequestBuilder<IngestEventResponse> {
        let localVariablePath = "/attribution/apple-search-ads"
        let localVariableURLString = GTMEasyGrowthAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: appleAttributionRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "x-gtm-growth-key": xGtmGrowthKey.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<IngestEventResponse>.Type = GTMEasyGrowthAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Submit a Google Play install referrer string
     
     - parameter xGtmGrowthKey: (header) SDK write key issued from the GTM Easy dashboard for this app. 
     - parameter playInstallReferrerRequest: (body)  
     - returns: IngestEventResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func attributionPlayInstallReferrerPost(xGtmGrowthKey: String, playInstallReferrerRequest: PlayInstallReferrerRequest) async throws -> IngestEventResponse {
        return try await attributionPlayInstallReferrerPostWithRequestBuilder(xGtmGrowthKey: xGtmGrowthKey, playInstallReferrerRequest: playInstallReferrerRequest).execute().body
    }

    /**
     Submit a Google Play install referrer string
     - POST /attribution/play-install-referrer
     - parameter xGtmGrowthKey: (header) SDK write key issued from the GTM Easy dashboard for this app. 
     - parameter playInstallReferrerRequest: (body)  
     - returns: RequestBuilder<IngestEventResponse> 
     */
    open class func attributionPlayInstallReferrerPostWithRequestBuilder(xGtmGrowthKey: String, playInstallReferrerRequest: PlayInstallReferrerRequest) -> RequestBuilder<IngestEventResponse> {
        let localVariablePath = "/attribution/play-install-referrer"
        let localVariableURLString = GTMEasyGrowthAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: playInstallReferrerRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "x-gtm-growth-key": xGtmGrowthKey.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<IngestEventResponse>.Type = GTMEasyGrowthAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Submit a web referrer URL + click id
     
     - parameter xGtmGrowthKey: (header) SDK write key issued from the GTM Easy dashboard for this app. 
     - parameter webReferrerRequest: (body)  
     - returns: IngestEventResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func attributionWebReferrerPost(xGtmGrowthKey: String, webReferrerRequest: WebReferrerRequest) async throws -> IngestEventResponse {
        return try await attributionWebReferrerPostWithRequestBuilder(xGtmGrowthKey: xGtmGrowthKey, webReferrerRequest: webReferrerRequest).execute().body
    }

    /**
     Submit a web referrer URL + click id
     - POST /attribution/web-referrer
     - parameter xGtmGrowthKey: (header) SDK write key issued from the GTM Easy dashboard for this app. 
     - parameter webReferrerRequest: (body)  
     - returns: RequestBuilder<IngestEventResponse> 
     */
    open class func attributionWebReferrerPostWithRequestBuilder(xGtmGrowthKey: String, webReferrerRequest: WebReferrerRequest) -> RequestBuilder<IngestEventResponse> {
        let localVariablePath = "/attribution/web-referrer"
        let localVariableURLString = GTMEasyGrowthAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: webReferrerRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "x-gtm-growth-key": xGtmGrowthKey.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<IngestEventResponse>.Type = GTMEasyGrowthAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
