//
// EventsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class EventsAPI {

    /**
     Record a tracked event
     
     - parameter xGtmGrowthKey: (header) SDK write key issued from the GTM Easy dashboard for this app. 
     - parameter trackEventRequest: (body)  
     - returns: IngestEventResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func eventsPost(xGtmGrowthKey: String, trackEventRequest: TrackEventRequest) async throws -> IngestEventResponse {
        return try await eventsPostWithRequestBuilder(xGtmGrowthKey: xGtmGrowthKey, trackEventRequest: trackEventRequest).execute().body
    }

    /**
     Record a tracked event
     - POST /events
     - Persists a single event and fans out to configured connectors (Meta CAPI, Google Ads, TikTok Events, PostHog, Sentry, Statsig). Idempotent on `(app, eventName, occurredAt, identityHash)`.
     - parameter xGtmGrowthKey: (header) SDK write key issued from the GTM Easy dashboard for this app. 
     - parameter trackEventRequest: (body)  
     - returns: RequestBuilder<IngestEventResponse> 
     */
    open class func eventsPostWithRequestBuilder(xGtmGrowthKey: String, trackEventRequest: TrackEventRequest) -> RequestBuilder<IngestEventResponse> {
        let localVariablePath = "/events"
        let localVariableURLString = GTMEasyGrowthAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: trackEventRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "x-gtm-growth-key": xGtmGrowthKey.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<IngestEventResponse>.Type = GTMEasyGrowthAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
