//
// MetaAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class MetaAPI {

    /**
     Health probe
     
     - returns: HealthResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func healthGet() async throws -> HealthResponse {
        return try await healthGetWithRequestBuilder().execute().body
    }

    /**
     Health probe
     - GET /health
     - returns: RequestBuilder<HealthResponse> 
     */
    open class func healthGetWithRequestBuilder() -> RequestBuilder<HealthResponse> {
        let localVariablePath = "/health"
        let localVariableURLString = GTMEasyGrowthAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<HealthResponse>.Type = GTMEasyGrowthAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
