//
// SkanAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class SkanAPI {

    /**
     SKAdNetwork postback receiver
     
     - parameter skanPostbackRequest: (body)  
     - returns: HealthResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func skanPostbackPost(skanPostbackRequest: SkanPostbackRequest) async throws -> HealthResponse {
        return try await skanPostbackPostWithRequestBuilder(skanPostbackRequest: skanPostbackRequest).execute().body
    }

    /**
     SKAdNetwork postback receiver
     - POST /skan/postback
     - Apple sends signed postbacks here when a SKAN install attribution wins. Body is verified against Apple's published JWKS before persistence.
     - parameter skanPostbackRequest: (body)  
     - returns: RequestBuilder<HealthResponse> 
     */
    open class func skanPostbackPostWithRequestBuilder(skanPostbackRequest: SkanPostbackRequest) -> RequestBuilder<HealthResponse> {
        let localVariablePath = "/skan/postback"
        let localVariableURLString = GTMEasyGrowthAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: skanPostbackRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<HealthResponse>.Type = GTMEasyGrowthAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
