//
// SurveysAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class SurveysAPI {

    /**
     Submit an onboarding-survey response
     
     - parameter xGtmGrowthKey: (header) SDK write key issued from the GTM Easy dashboard for this app. 
     - parameter submitSurveyRequest: (body)  
     - returns: SubmitSurveyResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func surveysPost(xGtmGrowthKey: String, submitSurveyRequest: SubmitSurveyRequest) async throws -> SubmitSurveyResponse {
        return try await surveysPostWithRequestBuilder(xGtmGrowthKey: xGtmGrowthKey, submitSurveyRequest: submitSurveyRequest).execute().body
    }

    /**
     Submit an onboarding-survey response
     - POST /surveys
     - Persists flexible onboarding-survey answers (one stored row per question, no 240-char truncation). A `survey.completed`/`survey.dismissed` lifecycle event is also recorded for the journey timeline + connector fan-out (`partial` submissions emit no event). Idempotent on `submissionId`.
     - parameter xGtmGrowthKey: (header) SDK write key issued from the GTM Easy dashboard for this app. 
     - parameter submitSurveyRequest: (body)  
     - returns: RequestBuilder<SubmitSurveyResponse> 
     */
    open class func surveysPostWithRequestBuilder(xGtmGrowthKey: String, submitSurveyRequest: SubmitSurveyRequest) -> RequestBuilder<SubmitSurveyResponse> {
        let localVariablePath = "/surveys"
        let localVariableURLString = GTMEasyGrowthAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: submitSurveyRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "x-gtm-growth-key": xGtmGrowthKey.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SubmitSurveyResponse>.Type = GTMEasyGrowthAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
