//
// UsersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class UsersAPI {

    /**
     Identify a user / upsert traits
     
     - parameter xGtmGrowthKey: (header) SDK write key issued from the GTM Easy dashboard for this app. 
     - parameter identifyUserRequest: (body)  
     - returns: IngestUserResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func usersPost(xGtmGrowthKey: String, identifyUserRequest: IdentifyUserRequest) async throws -> IngestUserResponse {
        return try await usersPostWithRequestBuilder(xGtmGrowthKey: xGtmGrowthKey, identifyUserRequest: identifyUserRequest).execute().body
    }

    /**
     Identify a user / upsert traits
     - POST /users
     - parameter xGtmGrowthKey: (header) SDK write key issued from the GTM Easy dashboard for this app. 
     - parameter identifyUserRequest: (body)  
     - returns: RequestBuilder<IngestUserResponse> 
     */
    open class func usersPostWithRequestBuilder(xGtmGrowthKey: String, identifyUserRequest: IdentifyUserRequest) -> RequestBuilder<IngestUserResponse> {
        let localVariablePath = "/users"
        let localVariableURLString = GTMEasyGrowthAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: identifyUserRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "x-gtm-growth-key": xGtmGrowthKey.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<IngestUserResponse>.Type = GTMEasyGrowthAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
