//
// WebhooksAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class WebhooksAPI {

    /**
     App Store Server Notifications V2
     
     - parameter appStoreWebhookRequest: (body)  
     - returns: GenericOkResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func webhookAppstorePost(appStoreWebhookRequest: AppStoreWebhookRequest) async throws -> GenericOkResponse {
        return try await webhookAppstorePostWithRequestBuilder(appStoreWebhookRequest: appStoreWebhookRequest).execute().body
    }

    /**
     App Store Server Notifications V2
     - POST /webhook/appstore
     - Apple sends signed payloads here when a subscription state changes (renew, refund, expire, etc).
     - parameter appStoreWebhookRequest: (body)  
     - returns: RequestBuilder<GenericOkResponse> 
     */
    open class func webhookAppstorePostWithRequestBuilder(appStoreWebhookRequest: AppStoreWebhookRequest) -> RequestBuilder<GenericOkResponse> {
        let localVariablePath = "/webhook/appstore"
        let localVariableURLString = GTMEasyGrowthAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: appStoreWebhookRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GenericOkResponse>.Type = GTMEasyGrowthAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Google Play Real-time Developer Notifications
     
     - parameter playStoreWebhookRequest: (body)  
     - returns: GenericOkResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func webhookPlaystorePost(playStoreWebhookRequest: PlayStoreWebhookRequest) async throws -> GenericOkResponse {
        return try await webhookPlaystorePostWithRequestBuilder(playStoreWebhookRequest: playStoreWebhookRequest).execute().body
    }

    /**
     Google Play Real-time Developer Notifications
     - POST /webhook/playstore
     - Pub/Sub-delivered notifications for Play subscription state changes + voided purchases.
     - parameter playStoreWebhookRequest: (body)  
     - returns: RequestBuilder<GenericOkResponse> 
     */
    open class func webhookPlaystorePostWithRequestBuilder(playStoreWebhookRequest: PlayStoreWebhookRequest) -> RequestBuilder<GenericOkResponse> {
        let localVariablePath = "/webhook/playstore"
        let localVariableURLString = GTMEasyGrowthAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: playStoreWebhookRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GenericOkResponse>.Type = GTMEasyGrowthAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
