//
// AppleAttributionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AppleAttributionRequest: Codable, JSONEncodable, Hashable {

    public enum Environment: String, Codable, CaseIterable {
        case production = "production"
        case staging = "staging"
        case development = "development"
    }
    public enum Platform: String, Codable, CaseIterable {
        case ios = "ios"
        case android = "android"
        case web = "web"
        case macos = "macos"
        case server = "server"
    }
    public static let appRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let appleAttributionTokenRule = StringRule(minLength: 10, maxLength: nil, pattern: nil)
    public private(set) var app: String
    public private(set) var environment: Environment? = .production
    public private(set) var userId: String?
    public private(set) var anonymousId: String?
    public private(set) var deviceId: String?
    /** Originating platform. */
    public private(set) var platform: Platform? = .ios
    public private(set) var appVersion: String?
    public private(set) var buildNumber: String?
    public private(set) var source: String? = "native"
    public private(set) var country: String?
    public private(set) var locale: String?
    public private(set) var timezone: String?
    public private(set) var occurredAt: Date?
    /** Free-form structured properties. Reserved keys: `_ctx` for SDK common context. */
    public private(set) var properties: [String: AnyCodable]?
    public private(set) var appleAttributionToken: String

    public init(app: String, environment: Environment? = .production, userId: String? = nil, anonymousId: String? = nil, deviceId: String? = nil, platform: Platform? = .ios, appVersion: String? = nil, buildNumber: String? = nil, source: String? = "native", country: String? = nil, locale: String? = nil, timezone: String? = nil, occurredAt: Date? = nil, properties: [String: AnyCodable]? = nil, appleAttributionToken: String) {
        self.app = app
        self.environment = environment
        self.userId = userId
        self.anonymousId = anonymousId
        self.deviceId = deviceId
        self.platform = platform
        self.appVersion = appVersion
        self.buildNumber = buildNumber
        self.source = source
        self.country = country
        self.locale = locale
        self.timezone = timezone
        self.occurredAt = occurredAt
        self.properties = properties
        self.appleAttributionToken = appleAttributionToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case app
        case environment
        case userId
        case anonymousId
        case deviceId
        case platform
        case appVersion
        case buildNumber
        case source
        case country
        case locale
        case timezone
        case occurredAt
        case properties
        case appleAttributionToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(app, forKey: .app)
        try container.encodeIfPresent(environment, forKey: .environment)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(anonymousId, forKey: .anonymousId)
        try container.encodeIfPresent(deviceId, forKey: .deviceId)
        try container.encodeIfPresent(platform, forKey: .platform)
        try container.encodeIfPresent(appVersion, forKey: .appVersion)
        try container.encodeIfPresent(buildNumber, forKey: .buildNumber)
        try container.encodeIfPresent(source, forKey: .source)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(locale, forKey: .locale)
        try container.encodeIfPresent(timezone, forKey: .timezone)
        try container.encodeIfPresent(occurredAt, forKey: .occurredAt)
        try container.encodeIfPresent(properties, forKey: .properties)
        try container.encode(appleAttributionToken, forKey: .appleAttributionToken)
    }
}

