//
// AppStoreWebhookRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AppStoreWebhookRequest: Codable, JSONEncodable, Hashable {

    public static let signedPayloadRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public private(set) var signedPayload: String

    public init(signedPayload: String) {
        self.signedPayload = signedPayload
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case signedPayload
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(signedPayload, forKey: .signedPayload)
    }
}

