//
// HealthResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HealthResponse: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case ok = "ok"
    }
    public private(set) var status: Status
    public private(set) var version: String

    public init(status: Status, version: String) {
        self.status = status
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(version, forKey: .version)
    }
}

