//
// IdentifyUserRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IdentifyUserRequest: Codable, JSONEncodable, Hashable {

    public enum Environment: String, Codable, CaseIterable {
        case production = "production"
        case staging = "staging"
        case development = "development"
    }
    public enum Platform: String, Codable, CaseIterable {
        case ios = "ios"
        case android = "android"
        case web = "web"
        case macos = "macos"
        case server = "server"
    }
    public static let appRule = StringRule(minLength: 1, maxLength: 64, pattern: nil)
    public private(set) var app: String
    public private(set) var environment: Environment? = .production
    /** Originating platform. */
    public private(set) var platform: Platform? = .ios
    public private(set) var userId: String?
    public private(set) var anonymousId: String?
    public private(set) var deviceId: String?
    public private(set) var appVersion: String?
    public private(set) var buildNumber: String?
    public private(set) var country: String?
    public private(set) var locale: String?
    public private(set) var timezone: String?
    /** Free-form structured properties. Reserved keys: `_ctx` for SDK common context. */
    public private(set) var traits: [String: AnyCodable]?

    public init(app: String, environment: Environment? = .production, platform: Platform? = .ios, userId: String? = nil, anonymousId: String? = nil, deviceId: String? = nil, appVersion: String? = nil, buildNumber: String? = nil, country: String? = nil, locale: String? = nil, timezone: String? = nil, traits: [String: AnyCodable]? = nil) {
        self.app = app
        self.environment = environment
        self.platform = platform
        self.userId = userId
        self.anonymousId = anonymousId
        self.deviceId = deviceId
        self.appVersion = appVersion
        self.buildNumber = buildNumber
        self.country = country
        self.locale = locale
        self.timezone = timezone
        self.traits = traits
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case app
        case environment
        case platform
        case userId
        case anonymousId
        case deviceId
        case appVersion
        case buildNumber
        case country
        case locale
        case timezone
        case traits
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(app, forKey: .app)
        try container.encodeIfPresent(environment, forKey: .environment)
        try container.encodeIfPresent(platform, forKey: .platform)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(anonymousId, forKey: .anonymousId)
        try container.encodeIfPresent(deviceId, forKey: .deviceId)
        try container.encodeIfPresent(appVersion, forKey: .appVersion)
        try container.encodeIfPresent(buildNumber, forKey: .buildNumber)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(locale, forKey: .locale)
        try container.encodeIfPresent(timezone, forKey: .timezone)
        try container.encodeIfPresent(traits, forKey: .traits)
    }
}

