//
// IngestUserResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IngestUserResponse: Codable, JSONEncodable, Hashable {

    public private(set) var user: IngestUserResponseUser
    public private(set) var warnings: [String]

    public init(user: IngestUserResponseUser, warnings: [String]) {
        self.user = user
        self.warnings = warnings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case user
        case warnings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(user, forKey: .user)
        try container.encode(warnings, forKey: .warnings)
    }
}

