//
// IngestEventResponseEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IngestEventResponseEvent: Codable, JSONEncodable, Hashable {

    public private(set) var id: String
    public private(set) var eventName: String

    public init(id: String, eventName: String) {
        self.id = id
        self.eventName = eventName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case eventName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(eventName, forKey: .eventName)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension IngestEventResponseEvent: Identifiable {}
