//
// IngestUserResponseUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IngestUserResponseUser: Codable, JSONEncodable, Hashable {

    public private(set) var identityHash: String

    public init(identityHash: String) {
        self.identityHash = identityHash
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case identityHash
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(identityHash, forKey: .identityHash)
    }
}

