//
// PlayStoreWebhookRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PlayStoreWebhookRequest: Codable, JSONEncodable, Hashable {

    public private(set) var message: PlayStoreWebhookRequestMessage
    public private(set) var subscription: String?

    public init(message: PlayStoreWebhookRequestMessage, subscription: String? = nil) {
        self.message = message
        self.subscription = subscription
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case subscription
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encodeIfPresent(subscription, forKey: .subscription)
    }
}

