//
// PlayStoreWebhookRequestMessage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PlayStoreWebhookRequestMessage: Codable, JSONEncodable, Hashable {

    public static let dataRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public private(set) var data: String
    public private(set) var attributes: [String: String]?
    public private(set) var messageId: String?
    public private(set) var publishTime: String?

    public init(data: String, attributes: [String: String]? = nil, messageId: String? = nil, publishTime: String? = nil) {
        self.data = data
        self.attributes = attributes
        self.messageId = messageId
        self.publishTime = publishTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case attributes
        case messageId
        case publishTime
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(data, forKey: .data)
        try container.encodeIfPresent(attributes, forKey: .attributes)
        try container.encodeIfPresent(messageId, forKey: .messageId)
        try container.encodeIfPresent(publishTime, forKey: .publishTime)
    }
}

