//
// RegistrationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RegistrationRequest: Codable, JSONEncodable, Hashable {

    public enum Environment: String, Codable, CaseIterable {
        case production = "production"
        case staging = "staging"
        case development = "development"
    }
    public enum Platform: String, Codable, CaseIterable {
        case ios = "ios"
        case android = "android"
        case web = "web"
        case macos = "macos"
        case server = "server"
    }
    public static let appRule = StringRule(minLength: 1, maxLength: 64, pattern: nil)
    public static let usernameRule = StringRule(minLength: nil, maxLength: 240, pattern: nil)
    public static let emailRule = StringRule(minLength: nil, maxLength: 320, pattern: nil)
    /** Optional; the server derives the app from the write key when omitted. */
    public private(set) var app: String?
    public private(set) var environment: Environment? = .production
    /** Defaults to the registered app's platform when omitted. */
    public private(set) var platform: Platform?
    public private(set) var userId: String?
    public private(set) var anonymousId: String?
    public private(set) var deviceId: String?
    public private(set) var username: String?
    public private(set) var email: String?
    public private(set) var appVersion: String?
    public private(set) var buildNumber: String?
    public private(set) var source: String? = "native"
    /** ISO-3166 alpha-2; server fills from Cloudflare if absent. */
    public private(set) var country: String?
    public private(set) var locale: String?
    public private(set) var timezone: String?
    public private(set) var attributionProvider: String?
    public private(set) var attributionId: String?
    public private(set) var occurredAt: Date?
    /** Free-form structured properties. Reserved keys: `_ctx` for SDK common context. */
    public private(set) var traits: [String: AnyCodable]?
    /** Free-form structured properties. Reserved keys: `_ctx` for SDK common context. */
    public private(set) var properties: [String: AnyCodable]?

    public init(app: String? = nil, environment: Environment? = .production, platform: Platform? = nil, userId: String? = nil, anonymousId: String? = nil, deviceId: String? = nil, username: String? = nil, email: String? = nil, appVersion: String? = nil, buildNumber: String? = nil, source: String? = "native", country: String? = nil, locale: String? = nil, timezone: String? = nil, attributionProvider: String? = nil, attributionId: String? = nil, occurredAt: Date? = nil, traits: [String: AnyCodable]? = nil, properties: [String: AnyCodable]? = nil) {
        self.app = app
        self.environment = environment
        self.platform = platform
        self.userId = userId
        self.anonymousId = anonymousId
        self.deviceId = deviceId
        self.username = username
        self.email = email
        self.appVersion = appVersion
        self.buildNumber = buildNumber
        self.source = source
        self.country = country
        self.locale = locale
        self.timezone = timezone
        self.attributionProvider = attributionProvider
        self.attributionId = attributionId
        self.occurredAt = occurredAt
        self.traits = traits
        self.properties = properties
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case app
        case environment
        case platform
        case userId
        case anonymousId
        case deviceId
        case username
        case email
        case appVersion
        case buildNumber
        case source
        case country
        case locale
        case timezone
        case attributionProvider
        case attributionId
        case occurredAt
        case traits
        case properties
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(app, forKey: .app)
        try container.encodeIfPresent(environment, forKey: .environment)
        try container.encodeIfPresent(platform, forKey: .platform)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(anonymousId, forKey: .anonymousId)
        try container.encodeIfPresent(deviceId, forKey: .deviceId)
        try container.encodeIfPresent(username, forKey: .username)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(appVersion, forKey: .appVersion)
        try container.encodeIfPresent(buildNumber, forKey: .buildNumber)
        try container.encodeIfPresent(source, forKey: .source)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(locale, forKey: .locale)
        try container.encodeIfPresent(timezone, forKey: .timezone)
        try container.encodeIfPresent(attributionProvider, forKey: .attributionProvider)
        try container.encodeIfPresent(attributionId, forKey: .attributionId)
        try container.encodeIfPresent(occurredAt, forKey: .occurredAt)
        try container.encodeIfPresent(traits, forKey: .traits)
        try container.encodeIfPresent(properties, forKey: .properties)
    }
}

