//
// RegistrationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RegistrationResponse: Codable, JSONEncodable, Hashable {

    public private(set) var user: RegistrationResponseUser
    public private(set) var event: RegistrationResponseEvent
    public private(set) var warnings: [String]

    public init(user: RegistrationResponseUser, event: RegistrationResponseEvent, warnings: [String]) {
        self.user = user
        self.event = event
        self.warnings = warnings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case user
        case event
        case warnings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(user, forKey: .user)
        try container.encode(event, forKey: .event)
        try container.encode(warnings, forKey: .warnings)
    }
}

