//
// RegistrationResponseUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RegistrationResponseUser: Codable, JSONEncodable, Hashable {

    public private(set) var identityHash: String
    public private(set) var principalId: String?

    public init(identityHash: String, principalId: String? = nil) {
        self.identityHash = identityHash
        self.principalId = principalId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case identityHash
        case principalId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(identityHash, forKey: .identityHash)
        try container.encodeIfPresent(principalId, forKey: .principalId)
    }
}

