//
// SkanPostbackRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SkanPostbackRequest: Codable, JSONEncodable, Hashable {

    public enum CoarseConversionValue: String, Codable, CaseIterable {
        case low = "low"
        case medium = "medium"
        case high = "high"
    }
    public static let conversionValueRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 63, exclusiveMaximum: false, multipleOf: nil)
    public private(set) var version: String
    public private(set) var adNetworkId: String
    public private(set) var campaignId: Int?
    public private(set) var sourceIdentifier: String?
    public private(set) var transactionId: String
    public private(set) var appId: Int
    public private(set) var attributionSignature: String
    public private(set) var redownload: Bool?
    public private(set) var sourceAppId: Int?
    public private(set) var sourceDomain: String?
    public private(set) var fidelityType: Int?
    public private(set) var conversionValue: Int?
    public private(set) var coarseConversionValue: CoarseConversionValue?
    public private(set) var didWin: Bool?
    public private(set) var postbackSequenceIndex: Int?

    public init(version: String, adNetworkId: String, campaignId: Int? = nil, sourceIdentifier: String? = nil, transactionId: String, appId: Int, attributionSignature: String, redownload: Bool? = nil, sourceAppId: Int? = nil, sourceDomain: String? = nil, fidelityType: Int? = nil, conversionValue: Int? = nil, coarseConversionValue: CoarseConversionValue? = nil, didWin: Bool? = nil, postbackSequenceIndex: Int? = nil) {
        self.version = version
        self.adNetworkId = adNetworkId
        self.campaignId = campaignId
        self.sourceIdentifier = sourceIdentifier
        self.transactionId = transactionId
        self.appId = appId
        self.attributionSignature = attributionSignature
        self.redownload = redownload
        self.sourceAppId = sourceAppId
        self.sourceDomain = sourceDomain
        self.fidelityType = fidelityType
        self.conversionValue = conversionValue
        self.coarseConversionValue = coarseConversionValue
        self.didWin = didWin
        self.postbackSequenceIndex = postbackSequenceIndex
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case version
        case adNetworkId = "ad-network-id"
        case campaignId = "campaign-id"
        case sourceIdentifier = "source-identifier"
        case transactionId = "transaction-id"
        case appId = "app-id"
        case attributionSignature = "attribution-signature"
        case redownload
        case sourceAppId = "source-app-id"
        case sourceDomain = "source-domain"
        case fidelityType = "fidelity-type"
        case conversionValue = "conversion-value"
        case coarseConversionValue = "coarse-conversion-value"
        case didWin = "did-win"
        case postbackSequenceIndex = "postback-sequence-index"
    }

    public private(set) var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(version, forKey: .version)
        try container.encode(adNetworkId, forKey: .adNetworkId)
        try container.encodeIfPresent(campaignId, forKey: .campaignId)
        try container.encodeIfPresent(sourceIdentifier, forKey: .sourceIdentifier)
        try container.encode(transactionId, forKey: .transactionId)
        try container.encode(appId, forKey: .appId)
        try container.encode(attributionSignature, forKey: .attributionSignature)
        try container.encodeIfPresent(redownload, forKey: .redownload)
        try container.encodeIfPresent(sourceAppId, forKey: .sourceAppId)
        try container.encodeIfPresent(sourceDomain, forKey: .sourceDomain)
        try container.encodeIfPresent(fidelityType, forKey: .fidelityType)
        try container.encodeIfPresent(conversionValue, forKey: .conversionValue)
        try container.encodeIfPresent(coarseConversionValue, forKey: .coarseConversionValue)
        try container.encodeIfPresent(didWin, forKey: .didWin)
        try container.encodeIfPresent(postbackSequenceIndex, forKey: .postbackSequenceIndex)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        version = try container.decode(String.self, forKey: .version)
        adNetworkId = try container.decode(String.self, forKey: .adNetworkId)
        campaignId = try container.decodeIfPresent(Int.self, forKey: .campaignId)
        sourceIdentifier = try container.decodeIfPresent(String.self, forKey: .sourceIdentifier)
        transactionId = try container.decode(String.self, forKey: .transactionId)
        appId = try container.decode(Int.self, forKey: .appId)
        attributionSignature = try container.decode(String.self, forKey: .attributionSignature)
        redownload = try container.decodeIfPresent(Bool.self, forKey: .redownload)
        sourceAppId = try container.decodeIfPresent(Int.self, forKey: .sourceAppId)
        sourceDomain = try container.decodeIfPresent(String.self, forKey: .sourceDomain)
        fidelityType = try container.decodeIfPresent(Int.self, forKey: .fidelityType)
        conversionValue = try container.decodeIfPresent(Int.self, forKey: .conversionValue)
        coarseConversionValue = try container.decodeIfPresent(CoarseConversionValue.self, forKey: .coarseConversionValue)
        didWin = try container.decodeIfPresent(Bool.self, forKey: .didWin)
        postbackSequenceIndex = try container.decodeIfPresent(Int.self, forKey: .postbackSequenceIndex)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("version")
        nonAdditionalPropertyKeys.insert("ad-network-id")
        nonAdditionalPropertyKeys.insert("campaign-id")
        nonAdditionalPropertyKeys.insert("source-identifier")
        nonAdditionalPropertyKeys.insert("transaction-id")
        nonAdditionalPropertyKeys.insert("app-id")
        nonAdditionalPropertyKeys.insert("attribution-signature")
        nonAdditionalPropertyKeys.insert("redownload")
        nonAdditionalPropertyKeys.insert("source-app-id")
        nonAdditionalPropertyKeys.insert("source-domain")
        nonAdditionalPropertyKeys.insert("fidelity-type")
        nonAdditionalPropertyKeys.insert("conversion-value")
        nonAdditionalPropertyKeys.insert("coarse-conversion-value")
        nonAdditionalPropertyKeys.insert("did-win")
        nonAdditionalPropertyKeys.insert("postback-sequence-index")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

