//
// SubmitSurveyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SubmitSurveyRequest: Codable, JSONEncodable, Hashable {

    public enum Environment: String, Codable, CaseIterable {
        case production = "production"
        case staging = "staging"
        case development = "development"
    }
    public enum Platform: String, Codable, CaseIterable {
        case ios = "ios"
        case android = "android"
        case web = "web"
        case macos = "macos"
        case server = "server"
    }
    public enum Status: String, Codable, CaseIterable {
        case completed = "completed"
        case partial = "partial"
        case dismissed = "dismissed"
    }
    public static let appRule = StringRule(minLength: 1, maxLength: 64, pattern: nil)
    public static let surveyIdRule = StringRule(minLength: 1, maxLength: 200, pattern: nil)
    public static let surveyVersionRule = StringRule(minLength: nil, maxLength: 64, pattern: nil)
    public static let surveyNameRule = StringRule(minLength: nil, maxLength: 200, pattern: nil)
    public static let submissionIdRule = StringRule(minLength: nil, maxLength: 200, pattern: nil)
    public static let responsesRule = ArrayRule(minItems: nil, maxItems: 50, uniqueItems: false)
    /** Optional; the server derives the app from the write key when omitted. */
    public private(set) var app: String?
    public private(set) var environment: Environment? = .production
    /** Defaults to the registered app's platform when omitted. */
    public private(set) var platform: Platform?
    public private(set) var userId: String?
    public private(set) var anonymousId: String?
    public private(set) var deviceId: String?
    public private(set) var surveyId: String
    public private(set) var surveyVersion: String?
    public private(set) var surveyName: String?
    /** Optional; server generates a UUID when omitted. Idempotency key for retries. */
    public private(set) var submissionId: String?
    public private(set) var status: Status? = .completed
    public private(set) var appVersion: String?
    public private(set) var locale: String?
    public private(set) var country: String?
    public private(set) var occurredAt: Date?
    /** Per-question answers (0–50). May be empty when status = dismissed. */
    public private(set) var responses: [SurveyResponseAnswer]?
    /** Free-form structured properties. Reserved keys: `_ctx` for SDK common context. */
    public private(set) var properties: [String: AnyCodable]?
    /** Optional submission-level extensibility payload (A/B variant, locale overrides, UI context…). Echoed onto every answer row; persisted to the `metadata` JSON column for JSONExtract-on-demand reads. */
    public private(set) var metadata: [String: AnyCodable]?

    public init(app: String? = nil, environment: Environment? = .production, platform: Platform? = nil, userId: String? = nil, anonymousId: String? = nil, deviceId: String? = nil, surveyId: String, surveyVersion: String? = nil, surveyName: String? = nil, submissionId: String? = nil, status: Status? = .completed, appVersion: String? = nil, locale: String? = nil, country: String? = nil, occurredAt: Date? = nil, responses: [SurveyResponseAnswer]? = nil, properties: [String: AnyCodable]? = nil, metadata: [String: AnyCodable]? = nil) {
        self.app = app
        self.environment = environment
        self.platform = platform
        self.userId = userId
        self.anonymousId = anonymousId
        self.deviceId = deviceId
        self.surveyId = surveyId
        self.surveyVersion = surveyVersion
        self.surveyName = surveyName
        self.submissionId = submissionId
        self.status = status
        self.appVersion = appVersion
        self.locale = locale
        self.country = country
        self.occurredAt = occurredAt
        self.responses = responses
        self.properties = properties
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case app
        case environment
        case platform
        case userId
        case anonymousId
        case deviceId
        case surveyId
        case surveyVersion
        case surveyName
        case submissionId
        case status
        case appVersion
        case locale
        case country
        case occurredAt
        case responses
        case properties
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(app, forKey: .app)
        try container.encodeIfPresent(environment, forKey: .environment)
        try container.encodeIfPresent(platform, forKey: .platform)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(anonymousId, forKey: .anonymousId)
        try container.encodeIfPresent(deviceId, forKey: .deviceId)
        try container.encode(surveyId, forKey: .surveyId)
        try container.encodeIfPresent(surveyVersion, forKey: .surveyVersion)
        try container.encodeIfPresent(surveyName, forKey: .surveyName)
        try container.encodeIfPresent(submissionId, forKey: .submissionId)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(appVersion, forKey: .appVersion)
        try container.encodeIfPresent(locale, forKey: .locale)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(occurredAt, forKey: .occurredAt)
        try container.encodeIfPresent(responses, forKey: .responses)
        try container.encodeIfPresent(properties, forKey: .properties)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}

