//
// SubmitSurveyResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SubmitSurveyResponse: Codable, JSONEncodable, Hashable {

    public private(set) var submissionId: String
    /** Number of answer rows persisted. */
    public private(set) var accepted: Int
    public private(set) var warnings: [String]

    public init(submissionId: String, accepted: Int, warnings: [String]) {
        self.submissionId = submissionId
        self.accepted = accepted
        self.warnings = warnings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case submissionId
        case accepted
        case warnings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(submissionId, forKey: .submissionId)
        try container.encode(accepted, forKey: .accepted)
        try container.encode(warnings, forKey: .warnings)
    }
}

