//
// SurveyResponseAnswer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SurveyResponseAnswer: Codable, JSONEncodable, Hashable {

    public static let questionIdRule = StringRule(minLength: 1, maxLength: 200, pattern: nil)
    public static let typeRule = StringRule(minLength: nil, maxLength: 40, pattern: nil)
    public static let questionTextRule = StringRule(minLength: nil, maxLength: 300, pattern: nil)
    public static let positionRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let choicesRule = ArrayRule(minItems: nil, maxItems: 50, uniqueItems: false)
    public static let choiceLabelsRule = ArrayRule(minItems: nil, maxItems: 50, uniqueItems: false)
    public static let textRule = StringRule(minLength: nil, maxLength: 2000, pattern: nil)
    public private(set) var questionId: String
    /** Question type. Known: single_choice | multi_choice | rating | scale | nps | boolean | text | link. Unknown values are stored as text. */
    public private(set) var type: String
    /** Human-readable prompt, for friendly dashboards. */
    public private(set) var questionText: String?
    public private(set) var position: Int?
    /** Option IDs (single_choice = one element). */
    public private(set) var choices: [String]?
    /** Optional parallel human labels for `choices`. */
    public private(set) var choiceLabels: [String]?
    /** rating | scale | nps numeric answer. */
    public private(set) var number: Double?
    /** Free-text answer (up to 2000 chars). */
    public private(set) var text: String?
    public private(set) var bool: Bool?
    public private(set) var skipped: Bool?
    /** Optional per-answer extensibility payload (answer timing, validation flags…). Merged OVER submission-level metadata. */
    public private(set) var metadata: [String: AnyCodable]?

    public init(questionId: String, type: String, questionText: String? = nil, position: Int? = nil, choices: [String]? = nil, choiceLabels: [String]? = nil, number: Double? = nil, text: String? = nil, bool: Bool? = nil, skipped: Bool? = nil, metadata: [String: AnyCodable]? = nil) {
        self.questionId = questionId
        self.type = type
        self.questionText = questionText
        self.position = position
        self.choices = choices
        self.choiceLabels = choiceLabels
        self.number = number
        self.text = text
        self.bool = bool
        self.skipped = skipped
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case questionId
        case type
        case questionText
        case position
        case choices
        case choiceLabels
        case number
        case text
        case bool
        case skipped
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(questionId, forKey: .questionId)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(questionText, forKey: .questionText)
        try container.encodeIfPresent(position, forKey: .position)
        try container.encodeIfPresent(choices, forKey: .choices)
        try container.encodeIfPresent(choiceLabels, forKey: .choiceLabels)
        try container.encodeIfPresent(number, forKey: .number)
        try container.encodeIfPresent(text, forKey: .text)
        try container.encodeIfPresent(bool, forKey: .bool)
        try container.encodeIfPresent(skipped, forKey: .skipped)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}

