//
// TrackEventRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TrackEventRequest: Codable, JSONEncodable, Hashable {

    public enum Environment: String, Codable, CaseIterable {
        case production = "production"
        case staging = "staging"
        case development = "development"
    }
    public enum Platform: String, Codable, CaseIterable {
        case ios = "ios"
        case android = "android"
        case web = "web"
        case macos = "macos"
        case server = "server"
    }
    public enum EventName: String, Codable, CaseIterable {
        case appPeriodFirstOpen = "app.first_open"
        case appPeriodOpened = "app.opened"
        case userPeriodCreated = "user.created"
        case sessionPeriodStarted = "session.started"
        case sessionPeriodEnded = "session.ended"
        case acquisitionPeriodAttributionResolved = "acquisition.attribution_resolved"
        case appStorePeriodProductPageViewed = "app_store.product_page_viewed"
        case appStorePeriodInstallAttributed = "app_store.install_attributed"
        case onboardingPeriodStarted = "onboarding.started"
        case onboardingPeriodCompleted = "onboarding.completed"
        case onboardingPeriodStepViewed = "onboarding.step_viewed"
        case onboardingPeriodStepCompleted = "onboarding.step_completed"
        case onboardingPeriodStepSkipped = "onboarding.step_skipped"
        case onboardingPeriodGoalSelected = "onboarding.goal_selected"
        case onboardingPeriodPermissionPrompted = "onboarding.permission_prompted"
        case onboardingPeriodPermissionGranted = "onboarding.permission_granted"
        case onboardingPeriodPermissionDenied = "onboarding.permission_denied"
        case activationPeriodCompleted = "activation.completed"
        case featurePeriodUsed = "feature.used"
        case featurePeriodFirstUsed = "feature.first_used"
        case pagePeriodViewed = "page.viewed"
        case buttonPeriodClicked = "button.clicked"
        case goalPeriodCompleted = "goal.completed"
        case paywallPeriodOpened = "paywall.opened"
        case paywallPeriodClosed = "paywall.closed"
        case paywallPeriodUpgradeClicked = "paywall.upgrade_clicked"
        case paywallPeriodUpgradeCancelled = "paywall.upgrade_cancelled"
        case paywallPeriodProductsRequested = "paywall.products_requested"
        case paywallPeriodProductsLoaded = "paywall.products_loaded"
        case paywallPeriodProductsFailed = "paywall.products_failed"
        case paywallPeriodOfferEligible = "paywall.offer_eligible"
        case paywallPeriodPlanSelected = "paywall.plan_selected"
        case paywallPeriodRestoreClicked = "paywall.restore_clicked"
        case paywallPeriodRestoreCompleted = "paywall.restore_completed"
        case paywallPeriodRestoreFailed = "paywall.restore_failed"
        case purchasePeriodStarted = "purchase.started"
        case purchasePeriodCompleted = "purchase.completed"
        case purchasePeriodFailed = "purchase.failed"
        case purchasePeriodRefunded = "purchase.refunded"
        case trialPeriodEligible = "trial.eligible"
        case trialPeriodIneligible = "trial.ineligible"
        case trialPeriodStarted = "trial.started"
        case trialPeriodConverted = "trial.converted"
        case trialPeriodCancelled = "trial.cancelled"
        case trialPeriodExpired = "trial.expired"
        case trialPeriodBillingRetryStarted = "trial.billing_retry_started"
        case subscriptionPeriodStarted = "subscription.started"
        case subscriptionPeriodRenewed = "subscription.renewed"
        case subscriptionPeriodCancelled = "subscription.cancelled"
        case subscriptionPeriodExpired = "subscription.expired"
        case subscriptionPeriodBillingIssue = "subscription.billing_issue"
        case subscriptionPeriodGracePeriodStarted = "subscription.grace_period_started"
        case subscriptionPeriodRecovered = "subscription.recovered"
        case subscriptionPeriodRefunded = "subscription.refunded"
        case subscriptionPeriodPriceIncreaseAccepted = "subscription.price_increase_accepted"
        case subscriptionPeriodPriceIncreaseDeclined = "subscription.price_increase_declined"
        case revenuePeriodReceived = "revenue.received"
        case referralPeriodSent = "referral.sent"
        case referralPeriodAccepted = "referral.accepted"
        case reviewPeriodPrompted = "review.prompted"
        case reviewPeriodSubmitted = "review.submitted"
        case notificationPeriodReceived = "notification.received"
        case notificationPeriodOpened = "notification.opened"
        case errorPeriodOccurred = "error.occurred"
    }
    public static let appRule = StringRule(minLength: 1, maxLength: 64, pattern: nil)
    public private(set) var app: String
    public private(set) var environment: Environment? = .production
    /** Originating platform. */
    public private(set) var platform: Platform? = .ios
    public private(set) var userId: String?
    public private(set) var anonymousId: String?
    public private(set) var deviceId: String?
    public private(set) var eventName: EventName
    public private(set) var appVersion: String?
    public private(set) var buildNumber: String?
    public private(set) var source: String? = "native"
    /** ISO-3166 alpha-2; server fills from Cloudflare if absent. */
    public private(set) var country: String?
    public private(set) var locale: String?
    public private(set) var timezone: String?
    public private(set) var attributionProvider: String?
    public private(set) var attributionId: String?
    public private(set) var occurredAt: Date?
    /** Free-form structured properties. Reserved keys: `_ctx` for SDK common context. */
    public private(set) var properties: [String: AnyCodable]?
    public private(set) var metricValue: Double?
    public private(set) var metricLabel: String?

    public init(app: String, environment: Environment? = .production, platform: Platform? = .ios, userId: String? = nil, anonymousId: String? = nil, deviceId: String? = nil, eventName: EventName, appVersion: String? = nil, buildNumber: String? = nil, source: String? = "native", country: String? = nil, locale: String? = nil, timezone: String? = nil, attributionProvider: String? = nil, attributionId: String? = nil, occurredAt: Date? = nil, properties: [String: AnyCodable]? = nil, metricValue: Double? = nil, metricLabel: String? = nil) {
        self.app = app
        self.environment = environment
        self.platform = platform
        self.userId = userId
        self.anonymousId = anonymousId
        self.deviceId = deviceId
        self.eventName = eventName
        self.appVersion = appVersion
        self.buildNumber = buildNumber
        self.source = source
        self.country = country
        self.locale = locale
        self.timezone = timezone
        self.attributionProvider = attributionProvider
        self.attributionId = attributionId
        self.occurredAt = occurredAt
        self.properties = properties
        self.metricValue = metricValue
        self.metricLabel = metricLabel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case app
        case environment
        case platform
        case userId
        case anonymousId
        case deviceId
        case eventName
        case appVersion
        case buildNumber
        case source
        case country
        case locale
        case timezone
        case attributionProvider
        case attributionId
        case occurredAt
        case properties
        case metricValue
        case metricLabel
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(app, forKey: .app)
        try container.encodeIfPresent(environment, forKey: .environment)
        try container.encodeIfPresent(platform, forKey: .platform)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(anonymousId, forKey: .anonymousId)
        try container.encodeIfPresent(deviceId, forKey: .deviceId)
        try container.encode(eventName, forKey: .eventName)
        try container.encodeIfPresent(appVersion, forKey: .appVersion)
        try container.encodeIfPresent(buildNumber, forKey: .buildNumber)
        try container.encodeIfPresent(source, forKey: .source)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(locale, forKey: .locale)
        try container.encodeIfPresent(timezone, forKey: .timezone)
        try container.encodeIfPresent(attributionProvider, forKey: .attributionProvider)
        try container.encodeIfPresent(attributionId, forKey: .attributionId)
        try container.encodeIfPresent(occurredAt, forKey: .occurredAt)
        try container.encodeIfPresent(properties, forKey: .properties)
        try container.encodeIfPresent(metricValue, forKey: .metricValue)
        try container.encodeIfPresent(metricLabel, forKey: .metricLabel)
    }
}

