//
// WebReferrerRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WebReferrerRequest: Codable, JSONEncodable, Hashable {

    public enum Environment: String, Codable, CaseIterable {
        case production = "production"
        case staging = "staging"
        case development = "development"
    }
    public enum Platform: String, Codable, CaseIterable {
        case ios = "ios"
        case android = "android"
        case web = "web"
        case macos = "macos"
        case server = "server"
    }
    public static let appRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let webReferrerRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public private(set) var app: String
    public private(set) var environment: Environment? = .production
    public private(set) var userId: String?
    public private(set) var anonymousId: String?
    /** Originating platform. */
    public private(set) var platform: Platform? = .web
    public private(set) var source: String? = "native"
    public private(set) var occurredAt: Date?
    public private(set) var webReferrer: String
    public private(set) var clickId: String?
    /** Free-form structured properties. Reserved keys: `_ctx` for SDK common context. */
    public private(set) var properties: [String: AnyCodable]?

    public init(app: String, environment: Environment? = .production, userId: String? = nil, anonymousId: String? = nil, platform: Platform? = .web, source: String? = "native", occurredAt: Date? = nil, webReferrer: String, clickId: String? = nil, properties: [String: AnyCodable]? = nil) {
        self.app = app
        self.environment = environment
        self.userId = userId
        self.anonymousId = anonymousId
        self.platform = platform
        self.source = source
        self.occurredAt = occurredAt
        self.webReferrer = webReferrer
        self.clickId = clickId
        self.properties = properties
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case app
        case environment
        case userId
        case anonymousId
        case platform
        case source
        case occurredAt
        case webReferrer
        case clickId
        case properties
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(app, forKey: .app)
        try container.encodeIfPresent(environment, forKey: .environment)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(anonymousId, forKey: .anonymousId)
        try container.encodeIfPresent(platform, forKey: .platform)
        try container.encodeIfPresent(source, forKey: .source)
        try container.encodeIfPresent(occurredAt, forKey: .occurredAt)
        try container.encode(webReferrer, forKey: .webReferrer)
        try container.encodeIfPresent(clickId, forKey: .clickId)
        try container.encodeIfPresent(properties, forKey: .properties)
    }
}

